###
get http://localhost:8888/.netlify/functions/readall

###
post http://localhost:8888/.netlify/functions/create
Content-Type:  application/json

{
"link": "https://minimalistbaker.com/italian-herb-crispy-baked-tofu/",
            "name": "Italian herb crispy baked tofu",
            "cat": "finger food"
}
